/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scans */
        get: operations["listScans"];
        put?: never;
        /** Start a new scan */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an archive (.zip, .tar, .tar.gz, .tgz) for sandboxed extraction and scanning */
        post: operations["uploadScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scan by id */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/filter findings for a scan */
        get: operations["getFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute risk bands from stored factors (no re-detection) */
        post: operations["rescoreScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System/file/asset graph for a scan */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/cbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CycloneDX 1.6 Cryptography BOM export */
        get: operations["getCbom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remediation plan for a scan */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Executive PDF report [Proposed full implementation is Phase 9; Phase 0 returns a placeholder PDF] */
        get: operations["getReportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update triage status/note for a finding */
        patch: operations["patchFindingTriage"];
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List policies */
        get: operations["listPolicies"];
        /** Create or replace a policy (id taken from the body) */
        put: operations["upsertPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a policy by id */
        get: operations["getPolicy"];
        /** Replace a policy at a specific id */
        put: operations["putPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/pqc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference catalog of standardized PQC algorithms (FIPS 203/204/205) */
        get: operations["getPqcCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            error: string;
            message: string;
        };
        /** @enum {string} */
        FindingKind: "algorithm" | "certificate" | "key" | "protocol" | "library";
        /** @enum {string} */
        Surface: "source" | "binary" | "certificate" | "config" | "image" | "manifest";
        /** @enum {string} */
        Family: "RSA" | "DSA" | "DH" | "ECDH" | "ECDSA" | "Ed25519" | "X25519" | "AES" | "ChaCha20" | "3DES" | "DES" | "RC4" | "Blowfish" | "MD5" | "SHA-1" | "SHA-2" | "SHA-3" | "HMAC" | "ML-KEM" | "ML-DSA" | "SLH-DSA";
        /** @enum {string} */
        CryptoFunction: "keygen" | "encrypt" | "decrypt" | "sign" | "verify" | "digest" | "tag" | "keyderive" | "unknown";
        /** @enum {string} */
        FindingSource: "ast" | "ast-reference" | "ast-protocol-string" | "source-constant" | "binary-symbol" | "binary-constant" | "binary-oid" | "x509-parser" | "pem-parser" | "ssh-key-parser" | "config-parser" | "manifest";
        /** @enum {string} */
        TriageStatus: "open" | "accepted-risk" | "false-positive" | "fixed";
        /** @enum {string} */
        ScanStatus: "queued" | "ingesting" | "scanning" | "scoring" | "done" | "failed";
        /** @enum {string} */
        RiskBand: "critical" | "high" | "medium" | "low";
        /** @enum {string} */
        Exposure: "external" | "internal" | "isolated" | "test";
        /** @enum {string} */
        Criticality: "mission-critical" | "high" | "medium" | "low";
        /** @enum {string} */
        GraphNodeType: "system" | "file" | "asset";
        Location: {
            path: string;
            line?: number | null;
            offset?: number | null;
            layer?: string | null;
        };
        RiskCost: {
            pkBytesDelta: number;
            wireBytesDelta: number;
            opMsDelta: number;
        };
        Recommendation: {
            action: string;
            target?: string | null;
            cost: components["schemas"]["RiskCost"];
        };
        Risk: {
            score: number;
            band: components["schemas"]["RiskBand"];
            V: number;
            F: number;
            U: number;
            E: number;
            K: number;
            X: number;
            Y: number;
            Z: number;
            moscaMargin: number;
            reason: string;
            classicallyBroken: boolean;
            hndl: boolean;
            needsReview: boolean;
        };
        Triage: {
            status?: components["schemas"]["TriageStatus"];
            note?: string | null;
        };
        TriagePatch: {
            status: components["schemas"]["TriageStatus"];
            note?: string | null;
        };
        /**
         * @example {
         *       "id": "finding_001",
         *       "kind": "algorithm",
         *       "surface": "source",
         *       "family": "RSA",
         *       "displayName": "RSA-2048 key generation",
         *       "keySize": 2048,
         *       "mode": null,
         *       "curve": null,
         *       "function": "keygen",
         *       "location": {
         *         "path": "src/main/java/com/example/auth/KeyService.java",
         *         "line": 42,
         *         "offset": null,
         *         "layer": null
         *       },
         *       "symbol": "KeyPairGenerator.generateKeyPair",
         *       "snippet": "KeyPairGenerator gen = KeyPairGenerator.getInstance(\"RSA\"); gen.initialize(2048);",
         *       "source": "ast",
         *       "confidence": 0.92,
         *       "risk": {
         *         "score": 76.95,
         *         "band": "critical",
         *         "V": 1,
         *         "F": 0.9,
         *         "U": 1,
         *         "E": 0.95,
         *         "K": 0.9,
         *         "X": 12,
         *         "Y": 8,
         *         "Z": 10,
         *         "moscaMargin": 10,
         *         "reason": "Shor-vulnerable asymmetric keygen on an externally-exposed, mission-critical path; shelf life plus migration time exceeds the analyst's CRQC horizon.",
         *         "classicallyBroken": false,
         *         "hndl": true,
         *         "needsReview": false
         *       },
         *       "recommendation": {
         *         "action": "Migrate to ML-KEM-768 for key establishment (hybrid with X25519 during transition)",
         *         "target": "ML-KEM-768",
         *         "cost": {
         *           "pkBytesDelta": 928,
         *           "wireBytesDelta": 832,
         *           "opMsDelta": 0.05
         *         }
         *       },
         *       "triage": {
         *         "status": "open",
         *         "note": null
         *       }
         *     }
         */
        Finding: {
            id: string;
            kind: components["schemas"]["FindingKind"];
            surface: components["schemas"]["Surface"];
            family: components["schemas"]["Family"] | null;
            displayName: string;
            keySize?: number | null;
            mode?: string | null;
            curve?: string | null;
            function: components["schemas"]["CryptoFunction"];
            location: components["schemas"]["Location"];
            symbol: string;
            snippet: string;
            source: components["schemas"]["FindingSource"];
            confidence: number;
            risk?: components["schemas"]["Risk"] | null;
            recommendation?: components["schemas"]["Recommendation"] | null;
            triage: components["schemas"]["Triage"];
        };
        FindingPage: {
            items: components["schemas"]["Finding"][];
            cursor?: string | null;
            total: number;
        };
        ScanStats: {
            files: number;
            bytes: number;
            seconds: number;
            mbPerSec: number;
            errors: number;
            skippedPrefilter: number;
        };
        BandCounts: {
            /** @default 0 */
            critical: number;
            /** @default 0 */
            high: number;
            /** @default 0 */
            medium: number;
            /** @default 0 */
            low: number;
        };
        /**
         * @example {
         *       "id": "scan_stub_001",
         *       "target": "example-monorepo",
         *       "status": "done",
         *       "stats": {
         *         "files": 482,
         *         "bytes": 18340221,
         *         "seconds": 3.9,
         *         "mbPerSec": 4.48,
         *         "errors": 0,
         *         "skippedPrefilter": 311
         *       },
         *       "bands": {
         *         "critical": 2,
         *         "high": 1,
         *         "medium": 2,
         *         "low": 1
         *       },
         *       "policyId": "policy_default",
         *       "crqcYears": 10,
         *       "startedAt": "2026-09-17T12:00:00Z",
         *       "finishedAt": "2026-09-17T12:00:04Z"
         *     }
         */
        Scan: {
            id: string;
            target: string;
            status: components["schemas"]["ScanStatus"];
            stats?: components["schemas"]["ScanStats"] | null;
            bands: components["schemas"]["BandCounts"];
            policyId: string;
            crqcYears: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            bundleHash?: string | null;
        };
        ScanCreate: {
            path?: string | null;
            policyId?: string | null;
            crqcYears?: number | null;
        };
        RescoreRequest: {
            crqcYears?: number | null;
            policyId?: string | null;
        };
        RescoreResult: {
            bands: components["schemas"]["BandCounts"];
            changed: components["schemas"]["Finding"][];
        };
        Context: {
            exposure: components["schemas"]["Exposure"];
            criticality: components["schemas"]["Criticality"];
            shelfLifeYears: number;
            migrationYears: number;
        };
        ContextWithGlob: components["schemas"]["Context"] & {
            glob: string;
        };
        /**
         * @example {
         *       "id": "policy_default",
         *       "name": "Default NTRO baseline",
         *       "crqcYears": 10,
         *       "default": {
         *         "exposure": "internal",
         *         "criticality": "medium",
         *         "shelfLifeYears": 5,
         *         "migrationYears": 3
         *       },
         *       "contexts": [
         *         {
         *           "glob": "**\/prod/**",
         *           "exposure": "external",
         *           "criticality": "mission-critical",
         *           "shelfLifeYears": 10,
         *           "migrationYears": 5
         *         },
         *         {
         *           "glob": "**\/test/**",
         *           "exposure": "test",
         *           "criticality": "low",
         *           "shelfLifeYears": 1,
         *           "migrationYears": 1
         *         }
         *       ]
         *     }
         */
        Policy: {
            id: string;
            name: string;
            crqcYears: number;
            default: components["schemas"]["Context"];
            contexts?: components["schemas"]["ContextWithGlob"][];
        };
        GraphNode: {
            id: string;
            type: components["schemas"]["GraphNodeType"];
            label: string;
            band?: components["schemas"]["RiskBand"] | null;
            score?: number | null;
            occurrences: number;
            parentId?: string | null;
        };
        GraphEdge: {
            source: string;
            target: string;
        };
        Graph: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        RemediationPlanItem: {
            findingId: string;
            band: components["schemas"]["RiskBand"];
            displayName: string;
            location: components["schemas"]["Location"];
            action: string;
            target?: string | null;
        };
        RemediationPlan: {
            scanId: string;
            /** Format: date-time */
            generatedAt: string;
            items: components["schemas"]["RemediationPlanItem"][];
        };
        /**
         * @example {
         *       "family": "ML-KEM",
         *       "displayName": "ML-KEM-768",
         *       "standard": "FIPS 203",
         *       "parameterSet": "ML-KEM-768",
         *       "securityCategory": 3,
         *       "publicKeyBytes": 1184,
         *       "ciphertextOrSignatureBytes": 1088,
         *       "notes": "Recommended default KEM parameter set (roughly AES-192 equivalent)."
         *     }
         */
        PqcCatalogEntry: {
            family: components["schemas"]["Family"];
            displayName: string;
            standard: string;
            parameterSet: string;
            securityCategory: number;
            publicKeyBytes?: number | null;
            ciphertextOrSignatureBytes?: number | null;
            notes: string;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** Format: date-time */
            time: string;
        };
        /** @description WebSocket frame shape for /scans/{scan_id}/events. eventId is the real, stored per-scan sequence number (stringified integer, starting at 1) -- pass the last one seen back as the `after` query param to resume. */
        ScanEvent: {
            /** @enum {string} */
            type: "progress" | "finding" | "stage" | "done" | "error";
            eventId: string;
            /** @enum {string} */
            stage?: "ingesting" | "scanning" | "scoring";
            filesProcessed?: number;
            totalFiles?: number;
            /** @description Real running count of findings by surface, e.g. {source: 3}. */
            bySurface?: {
                [key: string]: number;
            };
            findingId?: string;
            family?: string | null;
            findingCount?: number;
            scanId?: string;
            message?: string;
        };
    };
    responses: {
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
    };
    parameters: {
        ScanId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listScans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"][];
                };
            };
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Scan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
        };
    };
    uploadScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Source bundle archive (.zip, .tar, .tar.gz, .tgz)
                     */
                    file: string;
                    /** @description Optional policy ID to enforce */
                    policyId?: string;
                    /**
                     * @description Cryptographically Relevant Quantum Computer arrival horizon
                     * @default 10
                     */
                    crqcYears?: number;
                };
            };
        };
        responses: {
            /** @description Scan created from uploaded archive */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFindings: {
        parameters: {
            query?: {
                band?: components["schemas"]["RiskBand"];
                family?: components["schemas"]["Family"];
                surface?: components["schemas"]["Surface"];
                source?: components["schemas"]["FindingSource"];
                minConfidence?: number;
                needsReview?: boolean;
                q?: string;
                cursor?: string;
                limit?: number;
                sort?: "score" | "path" | "family";
            };
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
        };
    };
    rescoreScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescoreRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreResult"];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    getCbom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CycloneDX 1.6 BOM */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationPlan"];
                };
            };
        };
    };
    getReportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    patchFindingTriage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriagePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"][];
                };
            };
        };
    };
    upsertPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPqcCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PqcCatalogEntry"][];
                };
            };
        };
    };
}
