/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past cryptographic scans */
        get: operations["listScans"];
        put?: never;
        /** Launch a new scan */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scan details */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query findings for a scan with filtering and pagination */
        get: operations["getScanFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-score scan with new CRQC scenario horizon or policy */
        post: operations["rescoreScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crypto estate hierarchy graph (System -> File -> Asset) */
        get: operations["getScanGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/cbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download CycloneDX 1.6 Cryptographic Bill of Materials (CBOM) */
        get: operations["getScanCbom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remediation migration plan */
        get: operations["getScanPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Executive summary report in PDF [Proposed until backend ships it] */
        get: operations["getScanReportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Triage a cryptographic finding */
        patch: operations["triageFinding"];
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all assessment policies */
        get: operations["listPolicies"];
        put?: never;
        /** Create new assessment policy */
        post: operations["createPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get policy by ID */
        get: operations["getPolicy"];
        /** Update existing policy */
        put: operations["updatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/pqc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PQC algorithm specification catalog (size and latency) */
        get: operations["getPqcCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RiskBand: "critical" | "high" | "medium" | "low";
        RiskBands: {
            critical: number;
            high: number;
            medium: number;
            low: number;
        };
        /** @enum {string} */
        ScanStatus: "queued" | "ingesting" | "scanning" | "scoring" | "done" | "failed";
        ScanStats: {
            files: number;
            bytes: number;
            seconds: number;
            mbPerSec: number;
            errors: number;
            skippedPrefilter: number;
        };
        Scan: {
            id: string;
            target: string;
            status: components["schemas"]["ScanStatus"];
            stats: components["schemas"]["ScanStats"];
            bands: components["schemas"]["RiskBands"];
            policyId?: string;
            /** @default 10 */
            crqcYears: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        FindingLocation: {
            path: string;
            line: number;
            offset?: number;
            layer?: string;
        };
        FindingRisk: {
            score: number;
            band: components["schemas"]["RiskBand"];
            /** @description Vulnerability weight */
            V: number;
            /** @description Cryptographic Function weight */
            F: number;
            /** @description Mosca Urgency weight */
            U: number;
            /** @description System Exposure weight */
            E: number;
            /** @description Business Criticality weight */
            K: number;
            /** @description Data shelf life in years */
            X: number;
            /** @description Migration time in years */
            Y: number;
            /** @description Years until Cryptanalytically Relevant Quantum Computer */
            Z: number;
            /** @description X + Y - Z */
            moscaMargin: number;
            reason: string;
            classicallyBroken: boolean;
            /** @description Harvest Now Decrypt Later risk */
            hndl: boolean;
            /** @description True when confidence < 0.75 */
            needsReview: boolean;
        };
        RecommendationCost: {
            pkBytesDelta: number;
            wireBytesDelta: number;
            opMsDelta: number;
        };
        Recommendation: {
            action: string;
            target: string;
            cost: components["schemas"]["RecommendationCost"];
        };
        /** @enum {string} */
        TriageStatus: "open" | "accepted-risk" | "false-positive" | "fixed";
        Triage: {
            status: components["schemas"]["TriageStatus"];
            note?: string;
        };
        Finding: {
            id: string;
            kind: string;
            surface: string;
            family: string;
            displayName: string;
            keySize?: number;
            mode?: string;
            curve?: string;
            function?: string;
            location: components["schemas"]["FindingLocation"];
            symbol?: string;
            snippet?: string;
            source: string;
            confidence: number;
            risk: components["schemas"]["FindingRisk"];
            recommendation: components["schemas"]["Recommendation"];
            triage: components["schemas"]["Triage"];
        };
        RemediationPlanItem: {
            location: string;
            line: number;
            asset: string;
            score: number;
            band: components["schemas"]["RiskBand"];
            reason: string;
            mosca_margin: number;
            confidence: number;
            action: string;
            target: string;
        };
        GraphNode: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "system" | "file" | "asset";
            occurrences: number;
            /** @enum {string} */
            semanticClass: "shor" | "classically-broken" | "grover" | "quantum-safe-classical" | "pqc";
            riskScore: number;
            details?: Record<string, never>;
        };
        GraphEdge: {
            source: string;
            target: string;
            relationship: string;
        };
        PolicyContext: {
            /** @enum {string} */
            exposure: "external" | "internal" | "isolated" | "test";
            /** @enum {string} */
            criticality: "mission-critical" | "high" | "medium" | "low";
            shelfLifeYears: number;
            migrationYears: number;
        };
        PolicyRule: components["schemas"]["PolicyContext"] & {
            glob: string;
        };
        Policy: {
            id: string;
            name: string;
            /** @default 10 */
            crqcYears: number;
            default: components["schemas"]["PolicyContext"];
            contexts: components["schemas"]["PolicyRule"][];
        };
        PqcCatalogItem: {
            alg: string;
            class: string;
            pk_bytes: number;
            ct_or_sig_bytes: number;
            keygen_ms: number;
            op1?: string;
            op1_ms?: number;
            op2?: string;
            op2_ms?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    listScans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"][];
                };
            };
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Local filesystem path to scan */
                    path?: string;
                    policyId?: string;
                    /** @default 10 */
                    crqcYears?: number;
                };
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    policyId?: string;
                    /** @default 10 */
                    crqcYears?: number;
                };
            };
        };
        responses: {
            /** @description Scan accepted and queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Scan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getScanFindings: {
        parameters: {
            query?: {
                band?: "critical" | "high" | "medium" | "low";
                family?: string;
                surface?: string;
                source?: string;
                minConfidence?: number;
                needsReview?: boolean;
                q?: string;
                cursor?: string;
                limit?: number;
                sort?: "score_desc" | "score_asc" | "confidence_asc" | "location_asc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated findings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Finding"][];
                        total: number;
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
    rescoreScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    crqcYears?: number;
                    policyId?: string;
                };
            };
        };
        responses: {
            /** @description Re-scoring result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bands: components["schemas"]["RiskBands"];
                        changedFindings: {
                            id: string;
                            displayName: string;
                            previousBand: components["schemas"]["RiskBand"];
                            newBand: components["schemas"]["RiskBand"];
                            previousScore: number;
                            newScore: number;
                        }[];
                    };
                };
            };
        };
    };
    getScanGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph structure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodes: components["schemas"]["GraphNode"][];
                        edges: components["schemas"]["GraphEdge"][];
                    };
                };
            };
        };
    };
    getScanCbom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CycloneDX 1.6 CBOM with signature record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example CycloneDX */
                        bomFormat: string;
                        /** @example 1.6 */
                        specVersion: string;
                        serialNumber?: string;
                        components: Record<string, never>[];
                        signature: {
                            algorithm: string;
                            value: string;
                            publicKey?: string;
                        };
                    };
                };
            };
        };
    };
    getScanPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Remediation plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationPlanItem"][];
                };
            };
        };
    };
    getScanReportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binary PDF stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Not yet implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    triageFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["TriageStatus"];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Updated finding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"][];
                };
            };
        };
    };
    createPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description Policy created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description Policy updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPqcCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog of classical and PQC replacement specifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PqcCatalogItem"][];
                };
            };
        };
    };
}
