/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scans */
        get: operations["listScans"];
        put?: never;
        /** Start a new scan */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an archive (.zip, .tar, .tar.gz, .tgz) for sandboxed extraction and scanning */
        post: operations["uploadScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scan by id */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/filter findings for a scan */
        get: operations["getFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute risk bands from stored factors (no re-detection) */
        post: operations["rescoreScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System/file/asset graph for a scan */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/cbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CycloneDX 1.6 Cryptography BOM export */
        get: operations["getCbom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remediation plan for a scan */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Executive PDF report [Proposed full implementation is Phase 9; Phase 0 returns a placeholder PDF] */
        get: operations["getReportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update triage status/note for a finding */
        patch: operations["patchFindingTriage"];
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List policies */
        get: operations["listPolicies"];
        /** Create or replace a policy (id taken from the body) */
        put: operations["upsertPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a policy by id */
        get: operations["getPolicy"];
        /** Replace a policy at a specific id */
        put: operations["putPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/pqc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference catalog of standardized PQC algorithms (FIPS 203/204/205) */
        get: operations["getPqcCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all monitored scan targets */
        get: operations["listTargets"];
        put?: never;
        /** Register a new scan target */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get target by id */
        get: operations["getTarget"];
        put?: never;
        post?: never;
        /** Delete target */
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        /** Update target configuration */
        patch: operations["patchTarget"];
        trace?: never;
    };
    "/api/v1/targets/{id}/scan-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an immediate scan for a target */
        post: operations["scanTargetNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List snapshots for a target */
        get: operations["listTargetSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate cryptographic drift between two snapshots of a target */
        get: operations["getTargetDrift"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active and historical alerts */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge an alert */
        patch: operations["acknowledgeAlert"];
        trace?: never;
    };
    "/api/v1/probes/tls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe an endpoint for TLS cryptographic configuration */
        post: operations["probeTls"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/probes/ssh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe an endpoint for SSH cryptographic configuration */
        post: operations["probeSsh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List historical probe results */
        get: operations["listProbeResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hsm/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enumerate PKCS#11 / SoftHSM2 cryptographic keys and slots */
        get: operations["getHsmInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estate/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** High-level cryptographic estate posture and PQC readiness summary */
        get: operations["getEstateSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estate/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical estate risk trend over time */
        get: operations["getEstateTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify the cryptographic SHA-256 hash integrity of the audit log chain */
        get: operations["verifyAuditChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get crypto mass conservation coverage certificate for a scan */
        get: operations["getScanCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/coverage/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get per-artifact crypto mass conservation coverage for a scan */
        get: operations["getScanArtifactCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/residue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List crypto debt residue clusters across scans and targets */
        get: operations["listResidueClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/residue/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get details of a specific crypto debt residue cluster */
        get: operations["getResidueCluster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Transition state of a residue cluster (open -> promoted | excluded | accepted) */
        patch: operations["patchResidueCluster"];
        trace?: never;
    };
    "/api/v1/criticality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asset business criticalities and ownership mappings */
        get: operations["listAssetCriticalities"];
        /** Set or update asset business criticality mapping */
        put: operations["setAssetCriticality"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/criticality/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import asset business criticalities from CSV (CMDB bulk load) */
        post: operations["importAssetCriticalityCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cloud/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover cryptographic keys from cloud providers (AWS KMS via LocalStack) */
        get: operations["listCloudKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estate/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated crypto coverage and debt trends across the estate */
        get: operations["getEstateCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            error: string;
            message: string;
        };
        /** @enum {string} */
        FindingKind: "algorithm" | "certificate" | "key" | "protocol" | "library";
        /** @enum {string} */
        Surface: "source" | "binary" | "certificate" | "config" | "image" | "manifest" | "hardware-hsm";
        /** @enum {string} */
        Family: "RSA" | "DSA" | "DH" | "ECDH" | "ECDSA" | "Ed25519" | "X25519" | "AES" | "ChaCha20" | "3DES" | "DES" | "RC4" | "Blowfish" | "MD5" | "SHA-1" | "SHA-2" | "SHA-3" | "HMAC" | "ML-KEM" | "ML-DSA" | "SLH-DSA";
        /** @enum {string} */
        CryptoFunction: "keygen" | "encrypt" | "decrypt" | "sign" | "verify" | "digest" | "tag" | "keyderive" | "unknown";
        /** @enum {string} */
        FindingSource: "ast" | "ast-reference" | "ast-protocol-string" | "source-constant" | "binary-symbol" | "binary-constant" | "binary-oid" | "x509-parser" | "pem-parser" | "ssh-key-parser" | "config-parser" | "manifest";
        /** @enum {string} */
        TriageStatus: "open" | "accepted-risk" | "false-positive" | "fixed";
        /** @enum {string} */
        ScanStatus: "queued" | "ingesting" | "scanning" | "scoring" | "done" | "failed";
        /** @enum {string} */
        RiskBand: "critical" | "high" | "medium" | "low";
        /** @enum {string} */
        Exposure: "external" | "internal" | "isolated" | "test";
        /** @enum {string} */
        Criticality: "mission-critical" | "high" | "medium" | "low";
        /** @enum {string} */
        GraphNodeType: "system" | "file" | "asset";
        Location: {
            path: string;
            line?: number | null;
            offset?: number | null;
            layer?: string | null;
        };
        RiskCost: {
            pkBytesDelta: number;
            wireBytesDelta: number;
            opMsDelta: number;
        };
        Recommendation: {
            action: string;
            target?: string | null;
            cost: components["schemas"]["RiskCost"];
        };
        Risk: {
            score: number;
            band: components["schemas"]["RiskBand"];
            V: number;
            F: number;
            U: number;
            E: number;
            K: number;
            X: number;
            Y: number;
            Z: number;
            moscaMargin: number;
            reason: string;
            classicallyBroken: boolean;
            hndl: boolean;
            needsReview: boolean;
        };
        Triage: {
            status?: components["schemas"]["TriageStatus"];
            note?: string | null;
        };
        TriagePatch: {
            status: components["schemas"]["TriageStatus"];
            note?: string | null;
        };
        /**
         * @example {
         *       "id": "finding_001",
         *       "kind": "algorithm",
         *       "surface": "source",
         *       "family": "RSA",
         *       "displayName": "RSA-2048 key generation",
         *       "keySize": 2048,
         *       "mode": null,
         *       "curve": null,
         *       "function": "keygen",
         *       "location": {
         *         "path": "src/main/java/com/example/auth/KeyService.java",
         *         "line": 42,
         *         "offset": null,
         *         "layer": null
         *       },
         *       "symbol": "KeyPairGenerator.generateKeyPair",
         *       "snippet": "KeyPairGenerator gen = KeyPairGenerator.getInstance(\"RSA\"); gen.initialize(2048);",
         *       "source": "ast",
         *       "confidence": 0.92,
         *       "risk": {
         *         "score": 76.95,
         *         "band": "critical",
         *         "V": 1,
         *         "F": 0.9,
         *         "U": 1,
         *         "E": 0.95,
         *         "K": 0.9,
         *         "X": 12,
         *         "Y": 8,
         *         "Z": 10,
         *         "moscaMargin": 10,
         *         "reason": "Shor-vulnerable asymmetric keygen on an externally-exposed, mission-critical path; shelf life plus migration time exceeds the analyst's CRQC horizon.",
         *         "classicallyBroken": false,
         *         "hndl": true,
         *         "needsReview": false
         *       },
         *       "recommendation": {
         *         "action": "Migrate to ML-KEM-768 for key establishment (hybrid with X25519 during transition)",
         *         "target": "ML-KEM-768",
         *         "cost": {
         *           "pkBytesDelta": 928,
         *           "wireBytesDelta": 832,
         *           "opMsDelta": 0.05
         *         }
         *       },
         *       "triage": {
         *         "status": "open",
         *         "note": null
         *       }
         *     }
         */
        Finding: {
            id: string;
            kind: components["schemas"]["FindingKind"];
            surface: components["schemas"]["Surface"];
            family: components["schemas"]["Family"] | null;
            displayName: string;
            keySize?: number | null;
            mode?: string | null;
            curve?: string | null;
            function: components["schemas"]["CryptoFunction"];
            location: components["schemas"]["Location"];
            symbol: string;
            snippet: string;
            source: components["schemas"]["FindingSource"];
            confidence: number;
            risk?: components["schemas"]["Risk"] | null;
            recommendation?: components["schemas"]["Recommendation"] | null;
            triage: components["schemas"]["Triage"];
            negotiated?: boolean | null;
        };
        FindingPage: {
            items: components["schemas"]["Finding"][];
            cursor?: string | null;
            total: number;
        };
        ScanStats: {
            files: number;
            bytes: number;
            seconds: number;
            mbPerSec: number;
            errors: number;
            skippedPrefilter: number;
        };
        BandCounts: {
            /** @default 0 */
            critical: number;
            /** @default 0 */
            high: number;
            /** @default 0 */
            medium: number;
            /** @default 0 */
            low: number;
        };
        /**
         * @example {
         *       "id": "scan_stub_001",
         *       "target": "example-monorepo",
         *       "status": "done",
         *       "stats": {
         *         "files": 482,
         *         "bytes": 18340221,
         *         "seconds": 3.9,
         *         "mbPerSec": 4.48,
         *         "errors": 0,
         *         "skippedPrefilter": 311
         *       },
         *       "bands": {
         *         "critical": 2,
         *         "high": 1,
         *         "medium": 2,
         *         "low": 1
         *       },
         *       "policyId": "policy_default",
         *       "crqcYears": 10,
         *       "startedAt": "2026-09-17T12:00:00Z",
         *       "finishedAt": "2026-09-17T12:00:04Z"
         *     }
         */
        Scan: {
            id: string;
            target: string;
            status: components["schemas"]["ScanStatus"];
            stats?: components["schemas"]["ScanStats"] | null;
            bands: components["schemas"]["BandCounts"];
            policyId: string;
            crqcYears: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            bundleHash?: string | null;
        };
        ScanCreate: {
            path?: string | null;
            policyId?: string | null;
            crqcYears?: number | null;
        };
        RescoreRequest: {
            crqcYears?: number | null;
            policyId?: string | null;
        };
        RescoreResult: {
            bands: components["schemas"]["BandCounts"];
            changed: components["schemas"]["Finding"][];
        };
        Context: {
            exposure: components["schemas"]["Exposure"];
            criticality: components["schemas"]["Criticality"];
            shelfLifeYears: number;
            migrationYears: number;
        };
        ContextWithGlob: components["schemas"]["Context"] & {
            glob: string;
        };
        /**
         * @example {
         *       "id": "policy_default",
         *       "name": "Default NTRO baseline",
         *       "crqcYears": 10,
         *       "default": {
         *         "exposure": "internal",
         *         "criticality": "medium",
         *         "shelfLifeYears": 5,
         *         "migrationYears": 3
         *       },
         *       "contexts": [
         *         {
         *           "glob": "**\/prod/**",
         *           "exposure": "external",
         *           "criticality": "mission-critical",
         *           "shelfLifeYears": 10,
         *           "migrationYears": 5
         *         },
         *         {
         *           "glob": "**\/test/**",
         *           "exposure": "test",
         *           "criticality": "low",
         *           "shelfLifeYears": 1,
         *           "migrationYears": 1
         *         }
         *       ]
         *     }
         */
        Policy: {
            id: string;
            name: string;
            crqcYears: number;
            default: components["schemas"]["Context"];
            contexts?: components["schemas"]["ContextWithGlob"][];
        };
        GraphNode: {
            id: string;
            type: components["schemas"]["GraphNodeType"];
            label: string;
            band?: components["schemas"]["RiskBand"] | null;
            score?: number | null;
            occurrences: number;
            parentId?: string | null;
        };
        GraphEdge: {
            source: string;
            target: string;
        };
        Graph: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        RemediationPlanItem: {
            findingId: string;
            band: components["schemas"]["RiskBand"];
            displayName: string;
            location: components["schemas"]["Location"];
            action: string;
            target?: string | null;
        };
        RemediationPlan: {
            scanId: string;
            /** Format: date-time */
            generatedAt: string;
            items: components["schemas"]["RemediationPlanItem"][];
        };
        /**
         * @example {
         *       "family": "ML-KEM",
         *       "displayName": "ML-KEM-768",
         *       "standard": "FIPS 203",
         *       "parameterSet": "ML-KEM-768",
         *       "securityCategory": 3,
         *       "publicKeyBytes": 1184,
         *       "ciphertextOrSignatureBytes": 1088,
         *       "notes": "Recommended default KEM parameter set (roughly AES-192 equivalent)."
         *     }
         */
        PqcCatalogEntry: {
            family: components["schemas"]["Family"];
            displayName: string;
            standard: string;
            parameterSet: string;
            securityCategory: number;
            publicKeyBytes?: number | null;
            ciphertextOrSignatureBytes?: number | null;
            notes: string;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** Format: date-time */
            time: string;
        };
        /** @description WebSocket frame shape for /scans/{scan_id}/events. eventId is the real, stored per-scan sequence number (stringified integer, starting at 1) -- pass the last one seen back as the `after` query param to resume. */
        ScanEvent: {
            /** @enum {string} */
            type: "progress" | "finding" | "stage" | "done" | "error";
            eventId: string;
            /** @enum {string} */
            stage?: "ingesting" | "scanning" | "scoring";
            filesProcessed?: number;
            totalFiles?: number;
            /** @description Real running count of findings by surface, e.g. {source: 3}. */
            bySurface?: {
                [key: string]: number;
            };
            findingId?: string;
            family?: string | null;
            findingCount?: number;
            scanId?: string;
            message?: string;
        };
        /** @enum {string} */
        TargetKind: "repo" | "path" | "endpoint";
        Target: {
            id: string;
            name: string;
            kind: components["schemas"]["TargetKind"];
            uri: string;
            policyId: string;
            schedule: string;
            enabled: boolean;
            lastScanId?: string | null;
            /** Format: date-time */
            lastScanAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        TargetCreate: {
            name: string;
            kind: components["schemas"]["TargetKind"];
            uri: string;
            policyId: string;
            schedule: string;
            /** @default true */
            enabled: boolean;
        };
        TargetPatch: {
            name?: string | null;
            policyId?: string | null;
            schedule?: string | null;
            enabled?: boolean | null;
        };
        ScanSnapshot: {
            id: string;
            targetId: string;
            scanId: string;
            /** Format: date-time */
            takenAt: string;
            bands: {
                [key: string]: number;
            };
            totalFindings: number;
            stats: components["schemas"]["ScanStats"];
            /** @description Crypto Mass Conservation coverage ratio at the time of this snapshot (v1.0). */
            coverageRatio?: number | null;
            /** @description Unexplained residue mass at the time of this snapshot (v1.0). */
            residueMass?: number | null;
        };
        DriftChangedItem: {
            finding: components["schemas"]["Finding"];
            fromBand: components["schemas"]["RiskBand"];
            toBand: components["schemas"]["RiskBand"];
        };
        DriftSummary: {
            addedCount: number;
            resolvedCount: number;
            changedCount: number;
            netRiskDelta: number;
            coverageDelta?: number | null;
            residueMassDelta?: number | null;
        };
        Drift: {
            targetId: string;
            fromSnapshotId: string;
            toSnapshotId: string;
            added: components["schemas"]["Finding"][];
            resolved: components["schemas"]["Finding"][];
            changed: components["schemas"]["DriftChangedItem"][];
            summary: components["schemas"]["DriftSummary"];
        };
        /** @enum {string} */
        AlertType: "new-critical" | "cert-expiring" | "drift" | "probe-downgrade" | "residue-rise";
        Alert: {
            id: string;
            type: components["schemas"]["AlertType"];
            targetId: string;
            findingId?: string | null;
            severity: components["schemas"]["RiskBand"];
            message: string;
            /** Format: date-time */
            createdAt: string;
            acknowledged: boolean;
        };
        /** @enum {string} */
        ProbeProtocol: "tls" | "ssh";
        ProbeRequest: {
            targetId: string;
            host: string;
            port: number;
        };
        ProbeResult: {
            id: string;
            targetId: string;
            host: string;
            port: number;
            protocol: components["schemas"]["ProbeProtocol"];
            negotiated: Record<string, never>;
            supported: Record<string, never>[];
            /** Format: date-time */
            probedAt: string;
        };
        HsmKey: {
            type: string;
            size: number;
            label: string;
        };
        HsmSlot: {
            slot: number;
            label: string;
            keys: components["schemas"]["HsmKey"][];
        };
        HsmInventory: {
            slots: components["schemas"]["HsmSlot"][];
        };
        EstateSummary: {
            totalTargets: number;
            totalScans: number;
            totalFindings: number;
            criticalFindings: number;
            pqcReadinessScore: number;
            activeAlerts: number;
            /** @description Count of explicit AssetCriticality records with facing=internal (v1.0, PS clause i's internal/external split). */
            internalFacingAssets: number;
            /** @description Count of explicit AssetCriticality records with facing=external. */
            externalFacingAssets: number;
        };
        EstateTrendPoint: {
            date: string;
            avgRiskScore: number;
            criticalCount: number;
            totalFindings: number;
        };
        EstateTrend: {
            days: number;
            points: components["schemas"]["EstateTrendPoint"][];
        };
        AuditVerifyResponse: {
            /** @enum {string} */
            status: "valid" | "tampered";
            recordCount: number;
            headHash: string;
            details?: string | null;
        };
        CoverageCertificate: {
            scanId: string;
            artifactCount: number;
            totalMass: number;
            attributedMass: number;
            excludedMass: number;
            residueMass: number;
            coverageRatio: number;
            residueClusterCount: number;
            /** Format: date-time */
            computedAt: string;
        };
        ArtifactCoverage: {
            artifactHash: string;
            path: string;
            totalMass: number;
            attributed: number;
            excluded: number;
            residue: number;
            coverageRatio: number;
        };
        ResidueOccurrence: {
            artifactHash: string;
            path: string;
            range: number[];
        };
        /** @enum {string} */
        ResidueClusterState: "open" | "promoted" | "excluded" | "accepted";
        ResidueCluster: {
            id: string;
            contentHash: string;
            signalTypes: string[];
            magnitude: number;
            occurrences: components["schemas"]["ResidueOccurrence"][];
            state: components["schemas"]["ResidueClusterState"];
            justification?: string | null;
            owner?: string | null;
            /** Format: date-time */
            firstSeen: string;
            /** Format: date-time */
            lastSeen: string;
        };
        ResidueClusterPatch: {
            state: components["schemas"]["ResidueClusterState"];
            justification?: string | null;
            owner?: string | null;
        };
        /** @enum {string} */
        AssetFacing: "internal" | "external";
        /** @enum {string} */
        CriticalitySource: "manual" | "import";
        AssetCriticality: {
            targetId: string;
            pathPattern: string;
            criticality: components["schemas"]["Criticality"];
            businessOwner: string;
            dataClassification: string;
            facing: components["schemas"]["AssetFacing"];
            source: components["schemas"]["CriticalitySource"];
        };
        CriticalityImportResponse: {
            imported: number;
            records: components["schemas"]["AssetCriticality"][];
        };
        CloudKeyRecord: {
            provider: string;
            keyId: string;
            algorithm: string;
            keySize: number;
            rotationAgeDays: number;
            policyCompliant: boolean;
            identityId?: string | null;
        };
        CloudKeysResponse: {
            keys: components["schemas"]["CloudKeyRecord"][];
            roadmap: string;
        };
        TargetCoverageSummary: {
            targetId: string;
            targetName: string;
            coverageRatio: number;
            residueMass: number;
            totalMass: number;
        };
        EstateCoverage: {
            overallCoverageRatio: number;
            totalMass: number;
            attributedMass: number;
            excludedMass: number;
            residueMass: number;
            totalClusters: number;
            targets: components["schemas"]["TargetCoverageSummary"][];
        };
    };
    responses: {
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
    };
    parameters: {
        ScanId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listScans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"][];
                };
            };
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Scan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
        };
    };
    uploadScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Source bundle archive (.zip, .tar, .tar.gz, .tgz)
                     */
                    file: string;
                    /** @description Optional policy ID to enforce */
                    policyId?: string;
                    /**
                     * @description Cryptographically Relevant Quantum Computer arrival horizon
                     * @default 10
                     */
                    crqcYears?: number;
                };
            };
        };
        responses: {
            /** @description Scan created from uploaded archive */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getFindings: {
        parameters: {
            query?: {
                band?: components["schemas"]["RiskBand"];
                family?: components["schemas"]["Family"];
                surface?: components["schemas"]["Surface"];
                source?: components["schemas"]["FindingSource"];
                minConfidence?: number;
                needsReview?: boolean;
                q?: string;
                cursor?: string;
                limit?: number;
                sort?: "score" | "path" | "family";
            };
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
        };
    };
    rescoreScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescoreRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreResult"];
                };
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    getCbom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CycloneDX 1.6 BOM */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationPlan"];
                };
            };
        };
    };
    getReportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    patchFindingTriage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriagePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"][];
                };
            };
        };
    };
    upsertPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
        };
    };
    getPqcCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PqcCatalogEntry"][];
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Target created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    scanTargetNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan created and executed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTargetSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSnapshot"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTargetDrift: {
        parameters: {
            query: {
                /** @description Baseline snapshot ID */
                from: string;
                /** @description Target snapshot ID */
                to: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drift"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                acknowledged?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    probeTls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    probeSsh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listProbeResults: {
        parameters: {
            query?: {
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"][];
                };
            };
        };
    };
    getHsmInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HsmInventory"];
                };
            };
        };
    };
    getEstateSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstateSummary"];
                };
            };
        };
    };
    getEstateTrend: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstateTrend"];
                };
            };
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
        };
    };
    getScanCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageCertificate"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getScanArtifactCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactCoverage"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listResidueClusters: {
        parameters: {
            query?: {
                state?: components["schemas"]["ResidueClusterState"];
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidueCluster"][];
                };
            };
        };
    };
    getResidueCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidueCluster"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchResidueCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidueClusterPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidueCluster"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listAssetCriticalities: {
        parameters: {
            query?: {
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCriticality"][];
                };
            };
        };
    };
    setAssetCriticality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCriticality"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCriticality"];
                };
            };
        };
    };
    importAssetCriticalityCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalityImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listCloudKeys: {
        parameters: {
            query?: {
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudKeysResponse"];
                };
            };
        };
    };
    getEstateCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstateCoverage"];
                };
            };
        };
    };
}
